AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  steganography

  Sample SAM Template for steganography

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        ProcessedImageBucket: !Ref ProcessedImageBucket

Resources:

  ProcessImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image_handler/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          ProcessedImageBucket: !Ref ProcessedImageBucket
      Events:
        ProcessImage:
          Type: Api
          Properties:
            Path: /process
            Method: post
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
              - !Sub "arn:aws:s3:::${ProcessedImageBucket}"



  ProcessedImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: steganography-image-bucket
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"

        

Outputs:
  ImageProcessApi:
    Description: "API Gateway endpoint URL for Prod stage for Image Processing function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process/"
  ImageProcessFunction:
    Description: "Image Processing Lambda Function ARN"
    Value: !GetAtt ProcessImageFunction.Arn
